blog/urls.py
from django.urls import path
from . import views

app_name='blog'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('posts/<int:pk>/', views.detail, name='detail'),
    path('archives/<int:year>/<int:month>/', views.ArchiveView.as_view(), name='archive'),
    path('categories/<int:pk>', views.CategoryView.as_view(), name='category'),
    path('tags/<int:pk>', views.TagView.as_view(), name='tag'),
    path('about/', views.about, name='about'),
    path('search/', views.search, name='search'),
]

blogproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('comments.urls')),
]

comments/urls.py
from django.urls import path
from . import views

app_name='comments'
urlpatterns=[
    path('comment/<int:post_pk>', views.comment, name='comment'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from django.utils.html import strip_tags



class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=70)
    body = models.TextField()
    created_time = models.DateTimeField(default=timezone.now)
    modified_time = models.DateTimeField()
    excerpt = models.CharField(max_length=200, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    views = models.PositiveIntegerField(default=0, editable=False)

    class Meta:
        ordering=['-created_time']

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.modified_time = timezone.now()
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

comments/models.py
from django.db import models
from django.utils import timezone

class Comment(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    url = models.URLField(blank=True)
    text = models.TextField()
    created_time = models.DateTimeField(default=timezone.now)
    post = models.ForeignKey('blog.Post', on_delete=models.CASCADE)

    def __str__(self):
        return '{}: {}'.format(self.name, self.text[:20])

    class Meta:
        ordering = ['-created_time']

comments/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields=['name', 'email', 'url', 'text']

blog/views.py
from django.shortcuts import render, get_object_or_404, render_to_response
from .models import Post, Tag, Category
from django.views.generic import ListView, DetailView
from django.db.models import Q
import re
import markdown


class IndexView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'
    paginate_by = 3

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        paginator = context.get('paginator')
        page = context.get('page_obj')
        is_paginated = context.get('is_paginated')
        pagination_data = self.pagination_data(paginator, page, is_paginated)
        context.update(pagination_data)
        return context

    def pagination_data(self, paginator, page, is_paginated):
        if not is_paginated:
            return {}
        first = False
        last = False
        left_has_more = False
        right_has_more = False
        left = []
        right = []
        # number of pages number explicitly displayed
        step = 3
        page_num = page.number
        total_pages = paginator.num_pages
        page_range = paginator.page_range

        if page_num==1:
            right = page_range[page_num:min(page_num+step, total_pages)]
            if right[-1] < total_pages-1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True
        elif page_num == total_pages:
            if page_num - step > first+1:
                left_has_more = True
            left = page_range[max(page_num-1-step, 0):page_num-1]
            if left[0]>1:
                first = True
        else:
            left = page_range[max(page_num-step-1, 0):page_num-1]
            right = page_range[page_num:min(page_num+step, total_pages)]
            if left[0]>2:
                left_has_more = True
            if right[-1]<total_pages-1:
                right_has_more = True
            if left[0]>1:
                first = True
            if right[-1]<total_pages:
                last = True

        data = {
            'left':left,
            'right':right,
            'left_has_more':left_has_more,
            'right_has_more':right_has_more,
            'first':first,
            'last':last,
        }
        return data

def about(request):
    return render_to_response('about.html')

def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.body = markdown.markdown(post.body,
                extensions=[
                    'markdown.extensions.extra',
                    'markdown.extensions.codehilite',
                ])
    return render(request, 'blog/detail.html', {'post': post})

"""
class PostDetailView(DetailView):
    model = Post
    template_name='blog/detail.html'
    context_object_name = 'post'

    def get(self, request, *args, **kwargs):
        response = super(PostDetailView, self).get(request, *args, **kwargs)
        self.object.increase_views()
        return response

    def get_object(self, queryset=None):
        post = super().get_object(queryset=None)
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            'markdown.extensions.toc',
        ])
        post.body = md.convert(post.body)
        m = re.search(r'<div class="toc">\s*<ul>(.*)</ul>\s*</div>', md.toc, re.S)
        post.toc = m.group(1) if m is not None else ''
        return post
"""

class ArchiveView(IndexView):
    def get_queryset(self):
        return super(ArchiveView, self).get_queryset().filter(
            created_time__year = self.kwargs.get('year'),
            created_time__month = self.kwargs.get('month'))

class CategoryView(IndexView):
    def get_queryset(self):
        cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
        return super(CategoryView, self).get_queryset().filter(category=cate)

class TagView(IndexView):
    def get_queryset(self):
        ta = get_object_or_404(Tag, pk=self.kwargs.get('pk'))
        return super(TagView, self).get_queryset().filter(tags=ta)

def search(request):
    q = request.GET.get('q')
    error_msg = ''

    if not q:
        error_msg = "Please input searching keywords."
        return render(request, 'blog/index.html', {'error_msg': error_msg})
    post_list = Post.objects.filter(Q(title__icontains=q) | Q(body__icontains=q))
    return render(request, 'blog/index.html', {'error_msg': error_msg, 'post_list': post_list})

comments/views.py
from blog.models import Post
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_POST
from django.contrib import messages

from .forms import CommentForm

@require_POST
def comment(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
        messages.add_message(request, messages.SUCCESS, 'Successfully published!', extra_tags='success')
        return redirect(post)

    context={
        'post':post,
        'form':form,
    }
    messages.add_message(request, messages.ERROR, 'Sorry, comment publish failed, please fix errors in form to resubmit.', extra_tags='danger')
    return render(request, 'comments/preview.html', context=context)

templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block main %}

<img src="{% static 'blog/image/fanny.JPG' %}" width="300" height="300">
<br>
<p>Hi there, I'm Fanny, a software developer and a music&amp; movie lover. I'm so exciting to develop this blog system.
As there are so many beautiful things in life about LOVE, FAITH, DREAM and HOPE,
so I want to record and share all of them in my life with the world in this way.
</p>
<br>
<p>
<h4><b>1Corinthians 13:4-7</b></h4>
Love is patient, love is kind. It does not envy, it does not boast, it is not proud.
It does not dishonor others, it is not self-seeking, it is not easily angered, it keeps
no record of wrongs. Love does not delight in evil but rejoices with the truth. It always
protects, always trusts, always hopes, always perseveres.
</p>


{% endblock main%}

templates/base.html
{% load static %}
{% load blog_extras %}
<!DOCTYPE html>
<html>
    <head>
        <title>Black &amp; White</title>
        <link href="https://cdn.bootcss.com/highlight.js/9.15.8/styles/github.min.css" rel="stylesheet">

        <style>
            .codehilite {
            padding: 0;
            }

            img {
                margin-bottom:30px;
            }

            /* for block of numbers */
            .hljs-ln-numbers {
            -webkit-touch-callout: none;
            -webkit-user-select: none;
            -khtml-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;

            text-align: center;
            color: #ccc;
            border-right: 1px solid #CCC;
            vertical-align: top;
            padding-right: 5px;
            }

            .hljs-ln-n {
            width: 30px;
            }

            /* for block of code */
            .hljs-ln .hljs-ln-code {
            padding-left: 10px;
            white-space: pre;
            }
        </style>
        </head>

      <!-- meta -->
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">

      <!-- css -->
      <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
      <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
      <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
      <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">
      <link rel="stylesheet" href="{% static 'blog/css/monokai.css' %}">

      <!-- js -->
      <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
      <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
      <script src="{% static 'blog/js/pace.min.js' %}"></script>
      <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
  </head>
  <body>
    <div class="container">
        <header id="site-header">
            <div class="row">
                <div class="col-md-4 col-sm-5 col-xs-8">
                    <div class="logo">
                        <h1><a href="{% url 'blog:index' %}"><b>Black</b> &amp; White</a></h1>
                    </div>
                </div><!-- col-md-4 -->
                <div class="col-md-8 col-sm-7 col-xs-4">
                    <nav class="main-nav" role="navigation">
                        <div class="navbar-header">
                            <button type="button" id="trigger-overlay" class="navbar-toggle">
                                <span class="ion-navicon"></span>
                            </button>
                        </div>

                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                            <ul class="nav navbar-nav navbar-right">
                                <li class="cl-effect-11"><a href="{% url 'blog:index' %}">Home</a></li>
                                <li class="cl-effect-11"><a href="full-width.html">Blog</a></li>
                                <li class="cl-effect-11"><a href="{% url 'blog:about' %}">About</a></li>
                            </ul>
                        </div><!-- /.navbar-collapse -->
                    </nav>
                    <div id="header-search-box">
                        <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                        <div id="search-form" class="search-form">
                            <form role="search" method="get" id="searchform" action="{% url 'blog:search' %}">
                                <input type="search" name="q" placeholder="search" required>
                                <button type="submit"><span class="ion-ios-search-strong"></span></button>
                            </form>
                        </div>
                    </div>
                </div><!-- col-md-8 -->
            </div>
        </header>
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>{{ message }}
            </div>
            {% endfor %}
        {% endif %}
    </div>
    <div class="content-body">
        <div class="container">
            <div class="row">
                <main class="col-md-8">
                    {% block main %}
                    {% endblock main%}
                </main>
                <aside class="col-md-4">
                    {% block toc %}
                    {% endblock toc %}
                    {% show_recent_posts %}
                    {% show_archives %}
                    {% show_categories %}
                    {% show_tags %}
                <div class="rss">
                    <a href=""><span class="ion-social-rss-outline"></span>RSS Subscription</a>
                </div>
                </aside>
            </div>
        </div>
    </div>
    <footer id="site-footer">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <p class="copyright">&copy 2019 - Fanny's Blog</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- Mobile Menu -->
    <div class="overlay overlay-hugeinc">
        <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
        <nav>
            <ul>
                <li><a href="{% url 'blog:index' %}">Home</a></li>
                <li><a href="full-width.html">Blog</a></li>
                <li><a href="about.html">About</a></li>
            </ul>
        </nav>
    </div>
      <!-- other contents -->
      <script src="{% static 'blog/js/script.js' %}"></script>
      <script src="https://cdn.bootcss.com/highlight.js/9.15.8/highlight.min.js"></script>
      <script src="https://cdn.bootcss.com/highlightjs-line-numbers.js/2.7.0/highlightjs-line-numbers.min.js"></script>
      <script>
        hljs.initHighlightingOnLoad();
        hljs.initLineNumbersOnLoad();
      </script>
  </body>
</html>

templates/blog/detail.html
{% extends 'base.html' %}
{% load comments_extras %}

{% block main %}
<article class="post post-{{ post.pk }}">
    <header class="entry-header">
        <h1 class="entry-title">{{ post.title }}</h1>
        <div class="entry-meta">
            <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
            <span class="post-date"><a href="#"><time class="entry-date"
                                                      datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
            <span class="post-author"><a href="#">{{ post.author }}</a></span>
            <span class="comments-link"><a href="#comment-area">{{ post.comment_set.count }} comments</a></span>
            <span class="views-count"><a href="#">{{ post.views }} reads</a></span>
        </div>
    </header>
    <div class="entry-content clearfix">
        {{ post.body| safe }}
    </div>
    <section class="comment-area" id="comment-area">
        <h3>Comments</h3>
        {% show_comment_form post %}
        <div class="comment-list-panel">
            {% show_comments post %}
        </div>
    </section>
</article>
{% endblock main %}

templates/blog/inclusions/_archives.html
<div class="widget widget-archives">
    <h3 class="widget-title">Archives</h3>
    <ul>
        {% for date in date_list %}
        <li>
            <a href="{% url 'blog:archive' date.year date.month %}">{{ date.month }}/{{ date.year }}</a>
        </li>
        {% empty %}
            No archives yet!
        {% endfor %}
    </ul>
</div>

templates/blog/inclusions/_categories.html
<div class="widget widget-category">
    <h3 class="widget-title">Categories</h3>
    <ul>
        {% for category in category_list %}
        <li>
            <a href="{% url 'blog:category' category.pk %}">{{ category.name }} <span class="post-count">(13)</span></a>
        </li>
        {% empty %}
            No categories yet!
        {% endfor %}
    </ul>
</div>

templates/blog/inclusions/_recent_posts.html
<div class="widget widget-recent-posts">
    <h3 class="widget-title">Recent Posts</h3>
    <ul>
        {% for post in recent_post_list %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
        {% empty %}
            No posts yet!
        {% endfor %}
    </ul>
</div>

templates/blog/inclusions/_tags.html
<div class="widget widget-tag-cloud">
    <h3 class="widget-title">Tags</h3>
    <ul>
        {% for tag in tag_list %}
        <li>
            <a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}</a>
        </li>
        {% empty %}
            No tags yet!
        {% endfor %}
    </ul>
</div

templates/blog/index.html
{% extends 'base.html' %}
{% block main %}
    {% if error_msg %}
        <p>{{ error_msg }}</p>
    {% endif %}
    {% for post in post_list %}
        <article class="post post-{{ post.pk }}">
            <header class="entry-header">
                <h1 class="entry-title">
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </h1>
                <div class="entry-meta">
                    <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                    <span class="post-date"><a href="#"><time class="entry-date"
                                                                datetime="2012-11-09T23:15:57+00:00">{{ post.created_time }}</time></a></span>
                    <span class="post-author"><a href="#">{{ post.author }}</a></span>
                    <span class="comments-link"><a href="{{ post.get_absolute_url }}#comment-area">{{ post.comment_set.count }} comments</a></span>
                    <span class="views-count"><a href="#">{{ post.views }} reads</a></span>
                </div>
            </header>
            <div class="entry-content clearfix">
                <p>{{ post.excerpt }}</p>
                <div class="read-more cl-effect-14">
                    <a href="{{ post.get_absolute_url }}" class="more-link">Continue<span class="meta-nav">→</span></a>
                </div>
            </div>
        </article>
    {% empty %}
        <div class="no-post">No post published yet!</div>
    {% endfor %}

    <div class="pagination-simple">
    {% if is_paginated %}
        {% if first %}
            <a href="?page=1">1</a>
        {% endif %}
        {% if left_has_more %}
        <span>...</span>
        {% endif %}
        {% if left %}
            {% for l in left %}
                <a href="?page={{ l }}">{{ l }}</a>
            {% endfor %}
        {% endif %}
        <a href="?page={{ page_obj.number }}" style="color:crimson">{{ page_obj.number }}</a>
        {% if right %}
            {% for r in right %}
                <a href="?page={{ r }}">{{ r }}</a>
            {% endfor %}
        {% endif %}
        {% if right_has_more %}
        <span>...</span>
        {% endif %}
        {% if last %}
            <a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a>
        {% endif %}
    {% endif %}
    </div>
{% endblock main %}

templates/comments/inclusions/_form.html
<form action="{% url 'comments:comment' post.pk %}" method="post" class="comment-form">
    {% csrf_token%}
    <div class="row">
        <div class="col-md-4">
            <label for="{{ form.name.id_for_label }}">{{ form.name.label }}:</label>
            {{ form.name }}
            {{ form.name.errors }}
        </div>
        <div class="col-md-4">
            <label for="{{ form.email.id_for_label }}">{{ form.email.label }}:</label>
            {{ form.email }}
            {{ form.email.errors }}
        </div>
        <div class="col-md-4">
            <label for="{{ form.url.id_for_label }}">{{ form.url.label }}:</label>
            {{ form.url }}
            {{ form.url.errors }}
        </div>
        <div class="col-md-12">
            <label for="{{ form.text.id_for_label }}">{{ form.text.label }}:</label>
            {{ form.text }}
            {{ form.text.errors }}
            <button type="submit" class="comment-btn">Publish</button>
        </div>
    </div>
</form>

templates/comments/inclusions/_list.html
<h3>Comments, in total <span>{{ comment_count }}</span> comments</h3>
<ul class="comment-list list-unstyled">
    {% for comment in comment_list %}
        <li class="comment-item">
        <span class="nickname">{{ comment.name }}</span>
        <time class="submit-date" datetime="{{ comment.created_time }}">{{ comment.created_time }}</time>
        <div class="text">
            {{ comment.text|linebreaks }}
        </div>
        </li>
    {% empty %}
        No publishes yet!
    {% endfor %}
</ul>

templates/comments/preview.html
{% extends 'base.html' %}
{% load comments_extras %}

{% block main %}
    {% show_comment_form post form %}
{% endblock main %}